### ISSUE TITLE
Doesn't work on Firefox until disable/enable plugin action for every page load or reload

### ISSUE THREAD

**Issue by guneyozsan** [jasonlong/isometric-contributions#100]
On Firefox the plugin works only after clicking disable/enable plugin for each page load. Reloading the same page or loading some other page reverts back to default Github view until another disable/enable plugin action. Firefox developer edition 65.0b12.

**Comment by jasonlong** [comment]
Sorry, I haven't had a chance to dig into this yet. I believe FF has improved their add-on system recently so I'll try to revisit this soon.

PRs welcome if anyone else wants to check into it :)

**Comment by guneyozsan** [comment]
I can confirm it this fixes for me as well. Thanks @kiendang .

**Comment by kiendang** [comment]
Happy to help ❤️
