### ISSUE TITLE
Doesn't work if a tab selected

### ISSUE THREAD

**Issue by RussKie** [jasonlong/isometric-contributions#102]
The graph is not rendered in isometric projection if a specific project or a specific year are selected

Default:
![image](https://user-images.githubusercontent.com/4403806/54500016-88af5b80-496c-11e9-91b8-c0a83c530818.png)

Selected year:
![image](https://user-images.githubusercontent.com/4403806/54500021-9f55b280-496c-11e9-8bc1-d4fdc50d16f0.png)

Selected an org:
![image](https://user-images.githubusercontent.com/4403806/54500046-cf9d5100-496c-11e9-9d02-6399840dca42.png)

**Comment by guneyozsan** [comment]
Isometric view of the selection re-appears if the page is reloaded after making a selection.

**Comment by RussKie** [comment]
It works after a refresh, thank you.

**Comment by GinoPane** [comment]
Why this was closed? If you need to refresh the page it does not mean that the isometric view works correctly, it means exactly the opposite.

**Comment by guneyozsan** [comment]
@RussKie Agree that issue should stay open. Refresh is a UX hack, not an intended or expected functionality.
