### ISSUE TITLE
Change the contributions' colors

### ISSUE THREAD

**Issue by g1eny0ung** [jasonlong/isometric-contributions#105]
Hi @jasonlong , I made a chrome extension named [Github Colors Contributions](https://chrome.google.com/webstore/detail/nmlemiahmhcclpifhmpbjbikdgbndief).

It can change the contributions' colors as you like. Yesterday my friend recommended me the **isometric-contributions** chrome extension which you made. I found my extension can change the graph colors unexpectedly 😆. Our two extensions worked seamlessly!

Would you mind me share the isometric-contributions' repo link in [Github Colors Contributions](https://github.com/g1eny0ung/github-colors-contributions)'s README? Or we can paste our repo links in README each other? Look forward to your reply 😃. 

***The screenshot:***

![image](https://user-images.githubusercontent.com/15034155/56411605-e6103280-62b3-11e9-8961-b6832750e413.png)

**Comment by Fasani** [comment]
@g1eny0ung I just tried your plugin as I think it is a nice idea but when both are installed it seems to break quite badly.
