### ISSUE TITLE
Switching between views causes year list to move out of view

### ISSUE THREAD

**Issue by Nikhil-Wagh** [jasonlong/isometric-contributions#108]
When you switch between views (isometric and normal) the year list below it moves out of view. See the image below 
<img width="559" alt="Screenshot 2020-03-05 at 5 00 57 PM" src="https://user-images.githubusercontent.com/20404093/75977856-49727580-5f03-11ea-8854-b9018a453aab.png">

**Comment by PinkFlufflyLlama** [comment]
I'm experiencing that too on chrome. For me, the username under one's profile picture is also getting stretched vertically.

**Comment by HWZen** [comment]
Not only the year list, but also your name, become so strange.
But back to normal after refrash.

* normal
![image](https://user-images.githubusercontent.com/46065109/81546621-366d9d00-93ad-11ea-8790-0060d207fba5.png)

* After click
![image](https://user-images.githubusercontent.com/46065109/81546748-65840e80-93ad-11ea-957b-f29561cc8e3a.png)

* After refresh
![image](https://user-images.githubusercontent.com/46065109/81546896-9fedab80-93ad-11ea-8393-11b25d3a83e1.png)

**Comment by NdagiStanley** [comment]
Same for me.  
  
That said, I really like the extension. Thank you @jasonlong for putting this out here.

**Comment by dipunj** [comment]
Since github is updating it's frontend, so I guess a few things would break.

**Comment by jasonlong** [comment]
Sorry for not replying to this earlier. Thank you for the bug report. I'm going to make an update here soon to fix up a few problems.

**Comment by jasonlong** [comment]
Just an FYI that I have a branch locally where I've got this :bug: fixed along with some other updates. Should be ready in the next couple of days.
