### ISSUE TITLE
Colours are all wrong...

### ISSUE THREAD

**Issue by Fasani** [jasonlong/isometric-contributions#110]
It seems the isometric contributions plugin broke overnight... the colours are all wrong lol :-)

My goodness, what are these new colours?

Maybe you also want to add a 1px corner rounding to match the new style.

<img width="918" alt="Screenshot 2020-06-23 at 10 56 57" src="https://user-images.githubusercontent.com/448410/85383528-582b7980-b540-11ea-99fd-e0b5b5d818ca.png">

**Comment by jasonlong** [comment]
Oh I hadn't even noticed this color change yet. You must be in the feature preview for the new design updates. I'll get the extension updated shortly to honor the new github.com colors. Thanks for the heads-up.

**Comment by Fasani** [comment]
Your welcome, I enjoy seeing all my contributions in glorious 3D!

**Comment by Matt-Gleich** [comment]
I am doing this right now. Almost done

**Comment by jasonlong** [comment]
Closed by #111 :sparkles:
