### ISSUE TITLE
Display number of contributions when user hovers on a day

### ISSUE THREAD

**Issue by aviskarkc10** [jasonlong/isometric-contributions#115]
The 2D version has the following feature when we hover on a day. It'd be good to be able to show something similar.

![image](https://user-images.githubusercontent.com/13309631/86700602-f7686a80-c030-11ea-9d75-cd093a36834a.png)

**Comment by jasonlong** [comment]
I agree it would be nice, but it's not really feasible with this layout. See #54.

**Comment by aviskarkc10** [comment]
If you say so. Awesome extension btw :smile:
