### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by dephraiim** [jasonlong/isometric-contributions#117]
Hello, I don't this is the right place to say this but I have no where else to go. I want to create an extension for twitter and I was wondering, how does it feed the page with the converted chart. How it makes it stay until you leave the page? An explanation would help. Thank You.

**Comment by jasonlong** [comment]
@dephraiim When I was first learning about extensions, I followed a guide like this from Google: https://developer.chrome.com/extensions/getstarted

That should help you understand how things work.
