### ISSUE TITLE
Not rendering properly after recent firefox upgrade

### ISSUE THREAD

**Issue by subnut** [jasonlong/isometric-contributions#130]
After the latest firefox update, the colors are no longer visible. It's a transparent 3d figure

See your own profile - 
![](https://i.imgur.com/vAkkpQS.png)

Firefox version -
![image](https://user-images.githubusercontent.com/56714626/97559563-99a6c680-1a03-11eb-9264-0f5444560669.png)

**Comment by jasonlong** [comment]
Thanks for the report @subnut. Something must have changed on the GitHub side here because the Chrome extension is also broken. I'll get this fixed ASAP.

**Comment by jasonlong** [comment]
This has been fixed and updates (v 1.1.5) have been submitted to the Chrome and Mozilla stores.

**Comment by jasonlong** [comment]
Both Chrome and Mozilla versions 1.1.5 are now available.

**Comment by subnut** [comment]
:+1: Can confirm it works again. Thanks!

**Comment by subnut** [comment]
@jasonlong It broke again, most probably due to the color change to celebrate Halloween.

**Comment by jasonlong** [comment]
@subnut I noticed this too - just pushed out an update.
