### ISSUE TITLE
embed in iframe?

### ISSUE THREAD

**Issue by jimbrig** [jasonlong/isometric-contributions#132]
Is there a way that you know of to embed the isometric chart in an iframe on another website? Or, for example, your markdown GitHub Profile README?

**Comment by jasonlong** [comment]
@jimbrig Good question and something I haven't thought about tbh. This would be possible to implement, but there's no way (that I know of) now to do so. I'll keep this open to think about a little bit.

**Comment by jimbrig** [comment]
Found this today: https://dev.to/lowlighter/rendering-the-commit-calendar-in-isometric-view-2ccg

**Comment by jasonlong** [comment]
Oh nice, that seems like it would do the trick. I'm going to close this out for now since there's a nice alternative solution.
