### ISSUE TITLE
1 day loss @max. streak == 365

### ISSUE THREAD

**Issue by jehyunlee** [jasonlong/isometric-contributions#136]
A few days ago I've achieved 365 streaks.
Right on the next day, the streak was supposed to be 366, however it stayed as 365. On the very next day it became 366.

please check the screenshots from 7th to 9th Nov.

![1604884737724](https://user-images.githubusercontent.com/2725349/98490697-a209c780-2275-11eb-97bc-d5fc3ef77804.png)

![1604884748844](https://user-images.githubusercontent.com/2725349/98490701-a46c2180-2275-11eb-8212-4cce720a9ebf.png)

![1604884756098](https://user-images.githubusercontent.com/2725349/98490700-a3d38b00-2275-11eb-9408-8bf1de4cc07d.png)

**Comment by jasonlong** [comment]
The 3d graph is limited in the days it knows about by the regular 2d chart on the page. Since it never shows more than 1 year's worth of data, 365 days (+/- any days from partial weeks on the chart) is all it can display. This is a known limitation for the extension.

**Comment by jehyunlee** [comment]
Thanks for your kind answer.
I appreciate your efforts to make a great extension. :)
