### ISSUE TITLE
Graph doesn’t render

### ISSUE THREAD

**Issue by jasonlong** [jasonlong/isometric-contributions#147]
GitHub pushed some markup changes last night that broke the extension. I'll be fixing this today.

**Comment by jasonlong** [comment]
Version 1.1.10 has been tagged here and submitted to the Chrome and Mozilla stores. Should be available very :soon:.

**Comment by jonrohan** [comment]
Keeping you on your toes 👋🏻

**Comment by jasonlong** [comment]
![](https://i.imgflip.com/4wqe7n.jpg)
