### ISSUE TITLE
Feature: i18n

### ISSUE THREAD

**Issue by PassionPenguin** [jasonlong/isometric-contributions#153]
maybe we can add translations to the string `Enable....`? for better user experience~

**Comment by jasonlong** [comment]
I'm not sure which `Enable...` string you mean? The only instance I found in the repo is for the browser permission popup and I don't have any control over that.

**Comment by PassionPenguin** [comment]
> I'm not sure which `Enable...` string you mean? The only instance I found in the repo is for the browser permission popup and I don't have any control over that.

<img width="398" alt="Screen Shot 2021-03-08 at 11 51 27 PM" src="https://user-images.githubusercontent.com/41184947/110345130-35f37080-8069-11eb-9439-e12438150465.png">

😄

**Comment by jasonlong** [comment]
Yeah that's from this file (which I copied from somewhere else): 
https://github.com/jasonlong/isometric-contributions/blob/main/src/webext-domain-permission-toggle.js

Feel free to add the necessary i18n changes to that file if you like.

**Comment by PassionPenguin** [comment]
> Yeah that's from this file (which I copied from somewhere else):
> https://github.com/jasonlong/isometric-contributions/blob/main/src/webext-domain-permission-toggle.js
> 
> Feel free to add the necessary i18n changes to that file if you like.

I have no idea on Chrome extension... I will try to make it..
