### ISSUE TITLE
[Bug] Isometric chart not available after changing `Activity in <project>`

### ISSUE THREAD

**Issue by Pixel48** [jasonlong/isometric-contributions#156]
![issue](https://user-images.githubusercontent.com/42846410/112530718-110c3680-8da7-11eb-84e2-b8020bd8e1ad.gif)

**Comment by jasonlong** [comment]
I have a feeling this is related to #57 which I have a fix coming for soon.

**Comment by Pixel48** [comment]
Good to know

**Comment by Pixel48** [comment]
#57

**Comment by Snabilah43** [comment]
UNCLE AKIFF

**Comment by jasonlong** [comment]
Fixed in #158
