### ISSUE TITLE
use color to identify more information

### ISSUE THREAD

**Issue by kbrock** [jasonlong/isometric-contributions#159]
This is great

The location of the data tells us what day.
The columns adds what day of the week the activity occurred.

You added height to tell us how many commits were made.
This overlaps with the existing functionality of color to tell us how many commits.

Can we free up the color to tell us something else and not loose that opportunity?
There are a ton of possible other metrics to use here.

What kind of commit (PR, review, ..) in a stacked graph
What repo the commits went into.

Not sure what is feasible, you probably have a number of ideas.

For an individual project was thinking: Whether the build is passing, when there are releases. I may want to see what can be done there.

Also of note, gradients are difficult for people to gauge. So keep that in mind if/when you change the meaning of color.

On the other hand you may feel that the number of commits is important enough to warrant using up 2 bits of data instead of one.

Since height is self explanatory, you probably no longer need a key to tell people that more saturated of a color means more commits. But if you want to share more a granular view of quantities, you can have a band in the bar every so many commits (e.g.: 10) Alternatively you may want to have tick marks on the back wall to show numbers.

**Comment by jasonlong** [comment]
Thanks for your interest in this project @kbrock. At this time, the extension is mostly in maintenance mode. Most activity now is to fix things when GitHub changes the markup and the scraping breaks. I don't have any current plans to add more features.

Making the blocks represent more information could be interesting, but would drastically change the complexity of this extension. It simply walks through the 2d graph and renders a 3d representation. Anything beyond that would get into requiring API calls, etc.

You are, of course, welcome to fork the project to make a more data-rich version. 😄

**Comment by kbrock** [comment]
Thanks for humoring me @jasonlong - very fun extension for sure.
