### ISSUE TITLE
Business week streak

### ISSUE THREAD

**Issue by kbrock** [jasonlong/isometric-contributions#161]
To promote not working 24/7, is it possible to show a streak of work in terms of only working week days?

I guess different countries have different weekends. Not sure the best way to solve this problem. A grid of days of the week to count? This just made this simple feature request way too complicated.

If you can think of a simpler solution, then cool. Otherwise I guess just close this RFE

**Comment by jasonlong** [comment]
I have mixed feelings about showing the streak. When I was at GitHub, we had many discussions about this and we ultimately killed the streak from the standard graph. While I respect that this metric isn't important for everyone, many people have enjoyed having it as part of the extension. I don't have any plans to add various settings for how it's calculated.
