### ISSUE TITLE
Streaks and contributions for current date not visible 

### ISSUE THREAD

**Issue by parvg555** [jasonlong/isometric-contributions#168]
![github_isometric](https://user-images.githubusercontent.com/61341517/124294132-fcdd8f80-db74-11eb-839c-aaf6777524fa.JPG)

As you can see in the above image, whenever the option of current year is selected in the github timeline option. Current streaks and contributions for the current week are not shown. since the date is assumed to be 31st december for that year.

**Comment by jasonlong** [comment]
Thanks for the report @parvg555. I'll try to get this fixed :soon:.
