### ISSUE TITLE
The streak can't go above ~368/369

### ISSUE THREAD

**Issue by Supercip971** [jasonlong/isometric-contributions#187]
Currently the "real" streak I have is 430 and the isometric-contributions don't go above 369. 

But otherwise I would like to say that the extension is awesome!

**Comment by jasonlong** [comment]
Yes, this is a limitation of the extension based since only uses the graph data visible on the page. https://github.com/jasonlong/isometric-contributions/issues/136#issuecomment-723996704

**Comment by Supercip971** [comment]
sorry :sweat_smile:
