### ISSUE TITLE
Why asking for permissions on all websites

### ISSUE THREAD

**Issue by E011011101001** [jasonlong/isometric-contributions#191]
After the 1.1.16 update or the merge #190, the extension is now asking for permission to read and change all my data on all websites.
![Screen Shot](https://user-images.githubusercontent.com/50290471/145807783-65008e5e-59a8-4924-af98-cfd584e928b3.png)

Maybe it's a mistake on the manifest file? I don't understand why it needs so much permission.

**Comment by ndom91** [comment]
Yeah maybe limit the requested domains to just `*github*` or something like that. Its a bit unnerving to see a simple extension like this all of a sudden require such wide permissions..

https://github.com/jasonlong/isometric-contributions/blob/da8bc35d40ddfcd56eed7e96a6e2e5dce0f5ac37/src/manifest.json#L14

**Comment by jasonlong** [comment]
This was not an intentional change. I recently updated the manifest to v3 per Chrome's requirements and must have done this part incorrectly. Thanks for letting me know. I'll get this fixed today.

**Comment by jasonlong** [comment]
This _should_ be fixed in `1.1.17` 🤞🏼
