### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by Clayblockunova** [jasonlong/isometric-contributions#193]
Hello!
I'm Clayblockunova, a Microsoft Edge user. Migrating a Google Chrome extention to the new Microsoft Edge is not so hard. When will you do this?

**Comment by jasonlong** [comment]
Since Edge runs on macOS I should be able to do this. Thanks for the nudge :thumbsup:

**Comment by jasonlong** [comment]
I've submitted the extension the Microsoft and it's in review. Will follow up once approved.

**Comment by jasonlong** [comment]
Now available: https://microsoftedge.microsoft.com/addons/detail/github-isometric-contribu/hcicbpfcbdpfgibhlbphodkcbojakpej
