### ISSUE TITLE
All metrics are invalid with `NaN` or `0`

### ISSUE THREAD

**Issue by AlexV525** [jasonlong/isometric-contributions#222]
For example https://github.com/jasonlong

![image](https://user-images.githubusercontent.com/15884415/210926080-65218278-8cd7-40f2-8015-c80f73a2ee4f.png)

**Comment by Zxilly** [comment]
Same problem

**Comment by Leslie-Wong-H** [comment]
The same experience.

**Comment by gurezo** [comment]
me too.
I have confirmed the same phenomenon in Firefox and Chrome,
Firefox v108.0.2 (64 bit)
Chrome v108.0.5359.124（Official Build） （arm64）

**Comment by Anass001** [comment]
Same issue, thought it's a problem on my side.
Chrome v108.0.5359.125 (Official Build) (64-bit)

**Comment by thevinitgupta** [comment]
I am having the same issue

**Comment by AlexV525** [comment]
> And a possible fix can be parse contribution string with regex?

I managed to solve the issue with your idea and a regexp. See #224 for more of the fix.

**Comment by jasonlong** [comment]
Sorry for the delay everyone - I was traveling over the weekend. I checked out your fix @AlexV525 and it seems to work great. Thank you!

I'll merge this now and publish updated extensions after.

**Comment by jasonlong** [comment]
Still waiting for the Chrome extension to be approved. It's usually very fast, but it's been pending all day. Hopefully soon 🤞🏻
