### ISSUE TITLE
Bug that two UIs of button group are displayed.

### ISSUE THREAD

**Issue by george0528** [jasonlong/isometric-contributions#236]
My operating environment with that problem
OS: windows11
Browser: Chrome111.0.5563.65(latest)

I found a bug where two UIs for a group of buttons are displayed as shown in the following image.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/79493776/226185669-673db53d-55ed-44ab-8fa1-a49087a093fe.png">

**Comment by george0528** [comment]
Created a pull request
https://github.com/jasonlong/isometric-contributions/pull/237

**Comment by george0528** [comment]
@jasonlong 
Thank you for bringing this issue to my attention. I can confirm that I have thoroughly checked and I do not have two copies of the extension enabled.

**Comment by jasonlong** [comment]
Interesting. And you see 2 sets of buttons when you go to any profile page?

**Comment by george0528** [comment]
To investigate the cause, we created a console.log before the function that generates the UI as shown in the image.
<img width="597" alt="image" src="https://user-images.githubusercontent.com/79493776/226752553-f43576a5-5b69-431a-9d27-262c46180f32.png">

The results are shown in the following image.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/79493776/226753094-a22dde46-5db1-4065-899a-6830abaddff8.png">

**Comment by george0528** [comment]
> Interesting. And you see 2 sets of buttons when you go to any profile page?
Yes it does. But I found that the two sets of buttons appear only if I reload my browser.
For example, if you go from the Repositories tab to the OverView tag, only one set of buttons is displayed.

**Comment by george0528** [comment]
Since the settingsPromise process is asynchronous, I thought the cause was that the processing takes place after the observer callback.
Therefore, in the pull request I created, I tried to solve the problem by making the settingsPromise process synchronous using await.

**Comment by george0528** [comment]
@jasonlong 
My friend seems to be experiencing the same bug.
The bug started to occur after upgrading Chrome, so maybe that is the cause.

**Comment by jasonlong** [comment]
Thanks for the additional info @george0528. I'll get this merged today :thumbsup:
