### ISSUE TITLE
Duplicated 2D/3D buttons in Edge Add-ons store distribution

### ISSUE THREAD

**Issue by yew** [jasonlong/isometric-contributions#240]
Edge uses distribution in [Edge Add-ons](https://microsoftedge.microsoft.com/addons/detail/github-isometric-contribu/hcicbpfcbdpfgibhlbphodkcbojakpej).
<img width="700" alt="Edge Add-ons" src="https://user-images.githubusercontent.com/12381485/227867971-41df4df1-3e6e-4b51-abba-525709032d0b.png">

Edge uses distribution in [Chrome Web Store](https://chrome.google.com/webstore/detail/github-isometric-contribu/mjoedlfflcchnleknnceiplgaeoegien).
<img width="700" alt="Chrome Web Store" src="https://user-images.githubusercontent.com/12381485/227867474-dfe2752d-0cf5-4628-8744-ceffc29ba4a1.png">

**Comment by jasonlong** [comment]
I'm now seeing `1.1.24` in the store. I'm going to close this as the new version should fix the double button issue. Please reopen if you're still seeing the issue.

**Comment by yew** [comment]
@jasonlong thanks for your prompt response, I confirmed the issue is gone in `1.1.24`.
