### ISSUE TITLE
Incorrect End Date

### ISSUE THREAD

**Issue by zengshengliu** [jasonlong/isometric-contributions#243]
The end date of Contributions "This week" section and Streaks "Current" section seems to be incorrect.  I took the screenshot today (April 12), and both are showing April 8.
The streak calculation also seems to be wrong.
![image](https://user-images.githubusercontent.com/2967322/231496008-32c6d427-46a3-48a9-bb57-c92bde794ed7.png)

**Comment by jasonlong** [comment]
Thanks for reporting, @zengshengliu. I can reproduce this and will look into it!

**Comment by zengshengliu** [comment]
Hi @jasonlong 
it looks like the date is correct now, but the count is still off?
![image](https://user-images.githubusercontent.com/2967322/232245814-fb26917d-ffdd-4946-b194-2831c4aeb8e3.png)

**Comment by jasonlong** [comment]
@zengshengliu Has your extension updated to `1.1.25`? If your screenshot is from your profile, this is what I see:

<img width="772" alt="CleanShot 2023-04-15 at 16 29 17@2x" src="https://user-images.githubusercontent.com/6104/232251886-1e2cc36b-249b-4c00-b3a0-83a86567ff74.png">

**Comment by zengshengliu** [comment]
It looks like I am still on 1.1.24.  I don't see the update available in chrome store.  Is there a separate location where I can update it?

**Comment by jasonlong** [comment]
@zengshengliu It's still in the pending review state. Chrome used to have the fastest approval process and now it's taking several days.

**Comment by zengshengliu** [comment]
Looks like new version is live now and its working as expected.  Thanks.

**Comment by jasonlong** [comment]
Great!!
