### ISSUE TITLE
TypeError: Jr.toReversed is not a function

### ISSUE THREAD

**Issue by gurezo** [jasonlong/isometric-contributions#246]
### OS: Windows 11
![スクリーンショット 2023-04-16 210558](https://user-images.githubusercontent.com/7631567/232308710-5af9980e-7775-4973-9898-e934806a5025.png)

### case Firefox
![スクリーンショット 2023-04-16 210724](https://user-images.githubusercontent.com/7631567/232308847-ebd80216-148b-4bb8-8430-3c7f3d8c8eae.png)

```
[iso.js:229:28](moz-extension://d3207b8e-d6c0-4036-8963-3cdd1b02d1c1/src/iso.js)
```

![スクリーンショット 2023-04-16 210009](https://user-images.githubusercontent.com/7631567/232308595-660c270f-7dcd-4a5c-8ea6-313ee63fcc4d.png)

### case Chrome

![スクリーンショット 2023-04-16 211108](https://user-images.githubusercontent.com/7631567/232308964-709c6b55-df0d-4997-975e-314a9d7b1c4e.png)

```
iso.js:215 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dataset')
    at iso.js:215:35
```

![スクリーンショット 2023-04-16 205954](https://user-images.githubusercontent.com/7631567/232308587-14eb2a49-45ae-4625-b129-1d0610b98ac2.png)

**Comment by jasonlong** [comment]
Shoot, I didn't realize `toReversed` was unsupported in FF. I'll get this fixed.

@gurezo For the Chrome error, can you share which profile you're looking at when get this error? And you're using the latest code unpacked locally? It looks like `1.1.25` is still in review on the Chrome Web Store.

**Comment by gurezo** [comment]
@jasonlong 
Is this the information you need?
```
<html>
<body>
<!--StartFragment-->

Google Chrome | 112.0.5615.121 (Official Build) （64 ビット） (cohort: Stable Installs & Version Pins)
-- | --
変更履歴 | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | Windows 11 Version 22H2 (Build 22621.1555)
JavaScript | V8 11.2.214.14
ユーザー エージェント | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
コマンドライン | "C:\Program Files\Google\Chrome\Application\chrome.exe" --restart --restart --flag-switches-begin --flag-switches-end
実行ファイルのパス | C:\Program Files\Google\Chrome\Application\chrome.exe
プロフィール パス | C:\Users\XXXX\AppData\Local\Google\Chrome\User Data\Default

```

**Comment by jasonlong** [comment]
Thanks @gurezo. The latest version hasn't yet been approved on the Chrome Web Store, so let's hold off on that issue.

The Firefox one is a :bug: though - I should have a fix for that soon.

**Comment by jasonlong** [comment]
Version `1.1.26` has been submitted to the Mozilla Developer Hub which should fix this issue.
