### ISSUE TITLE
extension not work, Bar is flatten and Streaks is zero

### ISSUE THREAD

**Issue by gurezo** [jasonlong/isometric-contributions#280]
#### Chrome
![スクリーンショット 2023-10-18 18 43 46](https://github.com/jasonlong/isometric-contributions/assets/7631567/b9a602c8-33e4-40ba-b553-0ccdce2feb21)

#### Firefox
![スクリーンショット 2023-10-18 18 44 12](https://github.com/jasonlong/isometric-contributions/assets/7631567/2016ba85-95e3-413f-81cf-abdaebc62cc1)

### for macOS
![スクリーンショット 2023-10-18 18 42 42](https://github.com/jasonlong/isometric-contributions/assets/7631567/cbd49af6-0b82-4340-822d-01ffda4e76f4)

#### Chrome
![chome](https://github.com/jasonlong/isometric-contributions/assets/7631567/8f0a7570-3fb4-482b-811a-10edf0617d6b)

![スクリーンショット 2023-10-18 20 48 44](https://github.com/jasonlong/isometric-contributions/assets/7631567/376172a0-580a-412f-a653-f689b9b5e12f)

#### Firefox
![スクリーンショット 2023-10-18 18 43 05](https://github.com/jasonlong/isometric-contributions/assets/7631567/ce697a1a-4ec2-4cf2-ada7-9f507bc7e070)

![スクリーンショット 2023-10-18 20 48 08](https://github.com/jasonlong/isometric-contributions/assets/7631567/9930209f-5ef5-4517-a0a2-dd408d24e73a)

### for Windows
![windows11](https://github.com/jasonlong/isometric-contributions/assets/7631567/61808e85-07ad-43d8-a345-62213381faa6)

#### Chrome
![chrome](https://github.com/jasonlong/isometric-contributions/assets/7631567/81cb0202-8489-44da-8759-a6aa7fd26701)
![chrome-ex](https://github.com/jasonlong/isometric-contributions/assets/7631567/7116f3b9-7604-4940-a9b9-81491cb62007)

#### Firefox
![firefox](https://github.com/jasonlong/isometric-contributions/assets/7631567/cd2d92b6-ac7c-4647-8087-ea20c05876dc)
![firefox-ex](https://github.com/jasonlong/isometric-contributions/assets/7631567/7fb84260-3365-4a0c-8cd8-d0cbcce35488)

## Close conditions
- [ ] rendering Bar Graph
- [ ] Counting Streaks

**Comment by gurezo** [comment]
@jasonlong 

**It happened again**

## macOS
![スクリーンショット_2023-11-17_18_21_08](https://github.com/jasonlong/isometric-contributions/assets/7631567/2695ba6a-788c-45db-8698-99e60819e726)

### chrome
![スクリーンショット 2023-11-17 18 20 23](https://github.com/jasonlong/isometric-contributions/assets/7631567/c32c379b-91ff-4e03-87e3-02f084adbbda)
![スクリーンショット 2023-11-17 18 22 38](https://github.com/jasonlong/isometric-contributions/assets/7631567/9e40dce0-b2bc-4cda-a0da-372ee68efb93)

### firefox
![スクリーンショット 2023-11-17 18 20 42](https://github.com/jasonlong/isometric-contributions/assets/7631567/bc64c918-d363-460a-99b7-dfa35f1f36ba)
![スクリーンショット 2023-11-17 18 22 10](https://github.com/jasonlong/isometric-contributions/assets/7631567/14db41dc-ed16-4882-991f-20a8dba8eb2a)

## windows11
![スクリーンショット 2023-11-17 183227](https://github.com/jasonlong/isometric-contributions/assets/7631567/bd696a1f-b65d-4cdc-9dd3-7bbbccd52cfa)

### chrome
![スクリーンショット 2023-11-17 182851](https://github.com/jasonlong/isometric-contributions/assets/7631567/4ec5ed66-c38f-4f87-8f34-3ff2f0da496b)
![スクリーンショット 2023-11-17 182946](https://github.com/jasonlong/isometric-contributions/assets/7631567/e19bce7d-bcf3-4062-81d9-a949a43dafba)

### firefox
![スクリーンショット 2023-11-17 182647](https://github.com/jasonlong/isometric-contributions/assets/7631567/d81c856b-3773-4bba-93d3-ef67cd82f613)
![スクリーンショット 2023-11-17 183036](https://github.com/jasonlong/isometric-contributions/assets/7631567/266b1a19-e7c7-44d5-ae19-e97953dc830c)

**Comment by jasonlong** [comment]
Well this is frustrating. GitHub has reworked the markup for the contribution graph so that the daily count is no longer part of the `<td>` for each day. Instead each day has a separate `<tool-tip>` element that is associated with the `<td>` so the extension will need to be updated to fetch each tooltip to find the daily count.

I can try to look into this over the next few days, but if anyone else fixes it in the meantime please open a PR :bow:
