### ISSUE TITLE
Graph is flat with no data again

### ISSUE THREAD

**Issue by gurezo** [jasonlong/isometric-contributions#297]
@jasonlong 

#280  **It happened again**

## macOS
![スクリーンショット_2023-11-17_18_21_08](https://github.com/jasonlong/isometric-contributions/assets/7631567/2695ba6a-788c-45db-8698-99e60819e726)

### chrome
![スクリーンショット 2023-11-17 18 20 23](https://github.com/jasonlong/isometric-contributions/assets/7631567/c32c379b-91ff-4e03-87e3-02f084adbbda)
![スクリーンショット 2023-11-17 18 22 38](https://github.com/jasonlong/isometric-contributions/assets/7631567/9e40dce0-b2bc-4cda-a0da-372ee68efb93)
![スクリーンショット 2023-11-17 19 01 14](https://github.com/jasonlong/isometric-contributions/assets/7631567/c66d028d-d309-47a1-a9c5-ff64af08fa86)

### firefox
![スクリーンショット 2023-11-17 18 20 42](https://github.com/jasonlong/isometric-contributions/assets/7631567/bc64c918-d363-460a-99b7-dfa35f1f36ba)
![スクリーンショット 2023-11-17 18 22 10](https://github.com/jasonlong/isometric-contributions/assets/7631567/14db41dc-ed16-4882-991f-20a8dba8eb2a)
![スクリーンショット 2023-11-17 19 02 02](https://github.com/jasonlong/isometric-contributions/assets/7631567/517a9948-2e47-4b91-be3d-7c5a42138f32)

## windows11
![スクリーンショット 2023-11-17 183227](https://github.com/jasonlong/isometric-contributions/assets/7631567/bd696a1f-b65d-4cdc-9dd3-7bbbccd52cfa)

### chrome
![スクリーンショット 2023-11-17 182851](https://github.com/jasonlong/isometric-contributions/assets/7631567/4ec5ed66-c38f-4f87-8f34-3ff2f0da496b)
![スクリーンショット 2023-11-17 182946](https://github.com/jasonlong/isometric-contributions/assets/7631567/e19bce7d-bcf3-4062-81d9-a949a43dafba)
![スクリーンショット 2023-11-17 185911](https://github.com/jasonlong/isometric-contributions/assets/7631567/636f3bc9-88c4-482f-bef4-cd62391453fb)

### firefox
![スクリーンショット 2023-11-17 182647](https://github.com/jasonlong/isometric-contributions/assets/7631567/d81c856b-3773-4bba-93d3-ef67cd82f613)
![スクリーンショット 2023-11-17 183036](https://github.com/jasonlong/isometric-contributions/assets/7631567/266b1a19-e7c7-44d5-ae19-e97953dc830c)
![スクリーンショット 2023-11-17 185825](https://github.com/jasonlong/isometric-contributions/assets/7631567/fe420256-17a2-48f0-97b2-c96b10605a41)

## Close conditions
- [ ] rendering Bar Graph
- [ ] Counting Streaks

**Comment by jasonlong** [comment]
Well this is frustrating. GitHub has reworked the markup for the contribution graph so that the daily count is no longer part of the <td> for each day. Instead each day has a separate <tool-tip> element that is associated with the <td> so the extension will need to be updated to fetch each tooltip to find the daily count.

I can try to look into this over the next few days, but if anyone else fixes it in the meantime please open a PR 🙇

**Comment by jasonlong** [comment]
Fixed in #298. Browser extensions will update when approved by each store.
