### ISSUE TITLE
Stopped rendering (on Arc?)

### ISSUE THREAD

**Issue by texastoland** [jasonlong/isometric-contributions#309]
Stopped running at all yesterday after updating Arc.

Today I tried enabling it in incognito to test in isolation from other extensions. Also tried removing and re-adding it. Not only are the elements not in the DOM but the script isn't even in the sources panel and no errors in the console.

I assume it still works on Chrome? Other Arc users? Version info:

```
Version 1.36.0 (48035)
Chromium Engine Version 123.0.6312.87
```

**Comment by gurezo** [comment]
@jasonlong @texastoland 
me too.

Stopped rendering is follow os, browser version

### condition

![スクリーンショット 2024-03-30 18 09 48](https://github.com/jasonlong/isometric-contributions/assets/7631567/9a7fb4a2-2dfa-44b6-bee8-ecf5d39718bf)

### Windows

![スクリーンショット_2024-03-30_175204](https://github.com/jasonlong/isometric-contributions/assets/7631567/d3ebe7e4-8b5e-46d3-8c8d-9e7bd5d64092)

![スクリーンショット 2024-03-30 175413](https://github.com/jasonlong/isometric-contributions/assets/7631567/cc0d85ae-7d59-4d4c-b2d2-390ce73e22be)
![スクリーンショット 2024-03-30 175634](https://github.com/jasonlong/isometric-contributions/assets/7631567/efdb2137-f7ed-4cf6-969b-a2b1e27ad3b0)

### masOS

![スクリーンショット_2024-03-30_18_07_29](https://github.com/jasonlong/isometric-contributions/assets/7631567/b7a538b9-edb9-40b8-81b5-7ae33541ba4f)

![スクリーンショット 2024-03-30 18 03 02](https://github.com/jasonlong/isometric-contributions/assets/7631567/df4348bb-e44b-4216-9ba1-92753285da97)

![スクリーンショット 2024-03-30 18 01 02](https://github.com/jasonlong/isometric-contributions/assets/7631567/d3333dbc-5594-432a-9a6f-35f3e98ae2c0)

**Comment by jasonlong** [comment]
After a cursory look, it seems like GitHub now loads the profile page differently now and it doesn't trigger the extension as it used to (the check for the existence of a `.js-calendar-graph` node is returning false when it's really there).

I'll investigate more after the weekend.

**Comment by jasonlong** [comment]
I think I got this fixed. Submitting releases now.

**Comment by gurezo** [comment]
@jasonlong 

Thank you for your response
However, unfortunately there are some OS and browsers that are not compatible.

The only thing we were able to confirm was GitHub Isometric Contributions for Chrome on Windows.

Firefox remains unrendered on both Windows and macOS
The extension has been updated. I tried forcing a reload and refreshing Firefox, but the result was the same.

Same as GitHub Isometric Contributions for macOS Chrome.

## condition(Windows, macOS)

![スクリーンショット 2024-03-31 13 04 12](https://github.com/jasonlong/isometric-contributions/assets/7631567/9c5b085e-e56d-4d66-9ede-17faf9c529cc)

### Chrome Extension version

![スクリーンショット 2024-03-31 13 04 32](https://github.com/jasonlong/isometric-contributions/assets/7631567/2ceaf84d-1c8a-4523-890f-6e6189d63486)

### Firefox Extension version

![スクリーンショット 2024-03-31 13 04 47](https://github.com/jasonlong/isometric-contributions/assets/7631567/aecdc93f-d6c2-4df6-aa38-0fdc4dc53a00)


### matrix of extension that after improve

Browser | Windows | macOS
-- | -- | --
Chrome | O | X
Firefox | X | X
