### ISSUE TITLE
Doesn't display as usual 

### ISSUE THREAD

**Issue by kxxoling** [jasonlong/isometric-contributions#31]
One of the blocks is cut by the edge:

![github](https://cloud.githubusercontent.com/assets/1227139/5992710/3eb9dd98-aa6f-11e4-857e-a025868bb664.png)

BTW: Newest Chrome on OS X 10.10.

**Comment by jasonlong** [comment]
Yeah, this happens once in a while (see #27) and there's no good solution from what I can tell apart from making the graph much smaller.
