### ISSUE TITLE
Still Stopped rendering 

### ISSUE THREAD

**Issue by gurezo** [jasonlong/isometric-contributions#311]
@jasonlong 

Thank you for your response ( #309 )
However, unfortunately there are some OS and browsers that are not compatible.

The only thing we were able to confirm was GitHub Isometric Contributions for Chrome on Windows.

Firefox remains unrendered on both Windows and macOS
The extension has been updated. I tried forcing a reload and refreshing Firefox, but the result was the same.

Same as GitHub Isometric Contributions for macOS Chrome.

## condition(Windows, macOS)

![スクリーンショット 2024-03-31 13 04 12](https://github.com/jasonlong/isometric-contributions/assets/7631567/9c5b085e-e56d-4d66-9ede-17faf9c529cc)

### Chrome Extension version

![スクリーンショット 2024-03-31 13 04 32](https://github.com/jasonlong/isometric-contributions/assets/7631567/2ceaf84d-1c8a-4523-890f-6e6189d63486)

### Firefox Extension version

![スクリーンショット 2024-03-31 13 04 47](https://github.com/jasonlong/isometric-contributions/assets/7631567/aecdc93f-d6c2-4df6-aa38-0fdc4dc53a00)

### matrix of extension that after improve

Browser | Windows | macOS
-- | -- | --
Chrome | O | X
Firefox | X | X

**Comment by jasonlong** [comment]
Ok this will require a deeper dive when I'm back from traveling for Easter.

**Comment by gurezo** [comment]
@jasonlong 

> Ok this will require a deeper dive when I'm back from traveling for Easter.

Thank you for your reply even though you are on vacation!
We look forward to your corrections!

**Comment by texastoland** [comment]
> Same as GitHub Isometric Contributions for macOS Chrome.

Confirmed I just received `1.1.29` on (Chromium) Arc but same behavior. Enjoy your holiday 🐰

**Comment by jasonlong** [comment]
I've submitted `1.1.30` and the Firefox one is already available [here](https://addons.mozilla.org/en-US/firefox/addon/github-isometric-contributions/).

Should be available on the Chrome store very soon and Edge in a few days (they're much slower to review).

**Comment by Dev-Akash** [comment]
I'm also facing this issue on MacOS - in console logs i got this error from extention

> Uncaught SyntaxError: Cannot use import statement outside a module

I hope this helps in debugging.
Waiting for the fix.
Thanks!

**Comment by jasonlong** [comment]
`1.1.30` is available and is working for me. Please let me know if anyone sees issues still.

**Comment by texastoland** [comment]
WFM 🫚

**Comment by Dev-Akash** [comment]
Hi @jasonlong,
Thanks for that quick fix. It's working fine now on Chrome (MacOS)

**Comment by gurezo** [comment]
@jasonlong 

Operation has been confirmed.
The problem has been resolved.
thank you.

**Comment by jasonlong** [comment]
Awesome. FWIW with GitHub making changes so much more frequently on the profile page, I'm going to look into ways to automate periodic tests to catch when the extension stops working. Maybe with Puppeteer or something. If anyone has experience w/ this sort of thing lmk.
