### ISSUE TITLE
tighten permissions for chrome extension

### ISSUE THREAD

**Issue by wbolster** [jasonlong/isometric-contributions#32]
currently the chrome extension ask for permission to read data on any website, instead of just github (like some other github chrome extensions do). this doesn't feel right, so please tighten the permissions.

**Comment by jasonlong** [comment]
Unfortunately the current permissions are needed so that the extension can be used on Enterprise installations. See #16.

**Comment by wbolster** [comment]
okay, that explains. would be nice if there was a better way. anyway, thanks for the explanation.
