### ISSUE TITLE
No working after clicking 'Repositories'

### ISSUE THREAD

**Issue by montogeek** [jasonlong/isometric-contributions#35]
Hi!
Nice extension, I like the visualization.

I found a bug, when you open your profile, then click on the 'Repositories' tab and then click in the 'Contributions' tab the extension doesn't initialize.

**Comment by jasonlong** [comment]
Thanks @montogeek. This is a known issue unfortunately. I looked into it a while back and wasn't able to make the extension re-initialize in this scenario due to how those tabs load via pjax calls.

I'm going to close this for now, but would love to learn that this is actually possible.

**Comment by montogeek** [comment]
Thanks @jasonlong I will take a look how we can do this!
