### ISSUE TITLE
Request: Limit parsed websites to *.github.com and whitelist

### ISSUE THREAD

**Issue by doublerebel** [jasonlong/isometric-contributions#42]
Thanks for this extension!

Any chance we can get the address matches limited to *.github.com and a whitelist of sites?  For my own security sanity and to reduce overhead while browsing the net.  I see this has been requested but I do not fully understand how the current resolution was reached over a whitelist.

**Comment by jasonlong** [comment]
This has come up several times, but in order to allow the extension to work on GitHub Enterprise (which can be installed on any domain), this can't be done.

**Comment by doublerebel** [comment]
OK I can use another solution.  For anyone else looking, there is [an open issue for Chromium to restrict individual extensions](https://code.google.com/p/chromium/issues/detail?id=155743&q=java%20whitelist&colspec=ID%20Pri%20Mstone%20ReleaseBlock%20OS%20Area%20Feature%20Status%20Owner%20Summary) and until then there is an [extension to enable/disable extensions](https://chrome.google.com/webstore/detail/extension-automation/ghopjgdkodchjclkkfdekhjfomdbakkb).

**Comment by jasonlong** [comment]
Oh nice, thanks for those links @doublerebel. ✨
