### ISSUE TITLE
Firefox version doesn't show streaks?

### ISSUE THREAD

**Issue by joshcoales** [jasonlong/isometric-contributions#47]
It seems after the github change to remove streaks, the firefox version of this addon doesn't show streaks either?
![capture](https://cloud.githubusercontent.com/assets/2192223/15444487/3e9c76b4-1ee9-11e6-8582-363abfc750d9.PNG)

**Comment by jasonlong** [comment]
Ooof, sorry about that @joshcoales. I made a recent round of changes that must have broken FF. I'll take a look shortly.

**Comment by jasonlong** [comment]
Working on this in #49.

**Comment by jasonlong** [comment]
The new `.xpi` file should fix this problem.
