### ISSUE TITLE
Chrome doesn't show longest streak's end

### ISSUE THREAD

**Issue by nicolo-ribaudo** [jasonlong/isometric-contributions#48]
![github-iso-contribs](https://cloud.githubusercontent.com/assets/7000710/15506660/bf46e8ee-21c8-11e6-8a37-6d4a05f683f0.jpeg)

**Comment by jasonlong** [comment]
Thanks, I'll take a look.

**Comment by jasonlong** [comment]
This is fixed in `1.0.10`.
