### ISSUE TITLE
Need Firefox extension :)

### ISSUE THREAD

**Issue by julien-f** [jasonlong/isometric-contributions#5]
This is great!

Would it be possible to have a Firefox extension as well or maybe to make it cross-browsers (http://userscripts.org/)?

**Comment by ioana-chiorean** [comment]
:(

**Comment by asdofindia** [comment]
@jasonlong, Firefox is [adding web-extensions support](https://developer.mozilla.org/Add-ons/WebExtensions). 

But as of now, storage.local is not supported in content scripts.

I can make this working in Firefox 44 with only very few modifications (removing chrome.storage.local is the modification. And that removes the memory of the extension :( )

Checkout d1a41ad25ad6228a1437e3b23992e871fae14f34

**Comment by ioana-chiorean** [comment]
:tada:

**Comment by rileyjshaw** [comment]
Wow @asdofindia this is fantastic!!!!!
:tada: :tada: :tada:
