### ISSUE TITLE
longest streak < current streak in 1.0.10 (chrome Mac 51.0.2704.63 beta (64-bit))

### ISSUE THREAD

**Issue by Crossroadsman** [jasonlong/isometric-contributions#52]
Right now the chart is showing a longest streak of 3 days (Jan 30–Feb 1) but a current streak of 112 days (Feb 6–May 27). I would expect the period covered by the current streak to count towards the longest streak and therefore longest streak should never be less than current streak.

![screenshot 2016-05-27 23 05 48](https://cloud.githubusercontent.com/assets/5407045/15625322/99ea8c10-245f-11e6-9b7c-371e9940cafb.png)

**Comment by jasonlong** [comment]
I'm seeing 115 days for both of your streaks. If you're not seeing this, could you confirm that you have version 1.0.10 of the extension?

![screen shot 2016-05-31 at 7 58 07 am](https://cloud.githubusercontent.com/assets/6104/15673559/8eb3a2de-2705-11e6-90ad-be05820de706.png)

**Comment by Crossroadsman** [comment]
Hi Jason,

Thanks for the response. I can confirm that according to the Chrome extensions menu, I am running 1.1.10. Please see attached.
![screenshot 2016-05-31 18 14 52](https://cloud.githubusercontent.com/assets/5407045/15694539/e45bb07c-275b-11e6-933b-5436913866e2.png)
![screenshot 2016-05-31 18 13 53](https://cloud.githubusercontent.com/assets/5407045/15694541/e8196f92-275b-11e6-9623-9021bcff0194.png)
![screenshot 2016-05-31 18 13 14](https://cloud.githubusercontent.com/assets/5407045/15694542/ecb76c5c-275b-11e6-8ccc-3cf2dda99af5.png)

**Comment by jasonlong** [comment]
Very strange. I now see 116 for both streaks. The only difference I can see visually is that you have a green square for the current day on both screenshots and I've only seen your profile w/o a contribution for the current day. I'll keep an eye on your profile and try to see if the problem happens if/when the current day goes green.

**Comment by Crossroadsman** [comment]
Sounds good. Let me know if there's anything I can test on my end.

**Comment by Crossroadsman** [comment]
Now I'm wondering if the weirdness is on Github's end rather than the extension. I'm looking at yesterday's activity and this is what I see (zero contributions per the graph, but 1 contribution in the text immediately below):
![screenshot 2016-06-03 18 03 09](https://cloud.githubusercontent.com/assets/5407045/15796110/cf71c050-29b5-11e6-89a3-e19b593ff5e0.png)

I see the same thing on Chrome and Safari with your extension, and Safari Technology Preview without the extension. Weird.

**Comment by jasonlong** [comment]
Thanks for the extra info. I'm sort of at a loss for now, but let's keep an eye on it and see if any new clues emerge. Will leave this open for now.

**Comment by Crossroadsman** [comment]
Sounds good.
Thanks

**Comment by mkermani144** [comment]
I have the same issue with Chrome version 49 on Ubuntu.

**Comment by maasencioh** [comment]
Hello, for the user targos you can see also this issue, I'm currently using the version 1.0.12

![targos](https://cloud.githubusercontent.com/assets/7273940/19183585/4ee88c6c-8c79-11e6-8fe2-422a91c4553c.png)

**Comment by jasonlong** [comment]
Thanks @maasencioh, I was finally able to :eyes: this bug in action.
