### ISSUE TITLE
Limit Chrome permissions

### ISSUE THREAD

**Issue by cheshire137** [jasonlong/isometric-contributions#53]
Could you limit the required Chrome permissions to only require access to github.com?

<img width="470" alt="screen shot 2016-07-01 at 11 42 44 am" src="https://cloud.githubusercontent.com/assets/82317/16528208/fa23ae36-3f80-11e6-97cc-2050559e0492.png">

**Comment by jasonlong** [comment]
@cheshire137 Yeah, as we talked IRL, this was needed for supporting Enterprise. :(
