### ISSUE TITLE
on hover show count of contributions

### ISSUE THREAD

**Issue by prabhakar267** [jasonlong/isometric-contributions#54]
When a user hovers on the base of a bar, he should see a tooltip or something to see number of contributions  like he sees in normal chart view

**Comment by jasonlong** [comment]
This is intentionally not implemented because it would be impractical with so many columns being hidden behind others.

**Comment by prabhakar267** [comment]
So I think user should be given an option to rotate the whole graph so that he could see all the contributions!

**Comment by jasonlong** [comment]
The chart isn't a true 3D model (it uses obelisk.js) and therefore can't be rotated.

From the README:

> This isn't meant to completely replace the standard 2D graph though, because in most ways it is actually less useful. For example, there are no axis labels, shorter bars can be hidden behind taller ones, you can't hover over a bar to see the day and count, etc.
