### ISSUE TITLE
No longer works after GitHub's profile page redesign today

### ISSUE THREAD

**Issue by AlexNisnevich** [jasonlong/isometric-contributions#55]

**Comment by xwartz** [comment]
+1

**Comment by mkermani144** [comment]
:+1:

**Comment by jasonlong** [comment]
Yeah sorry about that. I was hoping to have the extension updated and ready to go before we shipped the profile updates. I'll get to this soon.

**Comment by nallwhy** [comment]
@jasonlong I created pull request for this problem.

**Comment by jasonlong** [comment]
This is mostly fixed (chart doesn't yet update on switching years) by @nallwhy in #56. 🎉
