### ISSUE TITLE
Isometric chart not available after changing years

### ISSUE THREAD

**Issue by jasonlong** [jasonlong/isometric-contributions#57]
When selecting a different year in the sidebar, the isometric chart and the chart buttons disappear.

**Comment by jasonlong** [comment]
Closed with #59.

**Comment by revolter** [comment]
This happens again, at least in Chrome.

**Comment by jasonlong** [comment]
Sorry for the delay! I see this as well and will work on a fix soon. Thanks for the heads up.

**Comment by jasonlong** [comment]
Fixed in #158
