### ISSUE TITLE
Additional Colors

### ISSUE THREAD

**Issue by Graystripe17** [jasonlong/isometric-contributions#63]
In addition to shades of green, would it be a good idea to have the option to display other colors?

**Comment by jasonlong** [comment]
The colors are meant to align with the standard contribution chart greens. What other colors were you thinking?

**Comment by Graystripe17** [comment]
Maybe purple or yellow. I realize that's not the standard Github theme, so this idea does not have to be implemented.

**Comment by Graystripe17** [comment]
Actually you can close this issue it won't hurt my feelings. I'm new at contributing to other repositories.

**Comment by jasonlong** [comment]
Yeah, I think it's best to stick with the standard green palette to avoid confusion.

On a related note, did you notice that we have our Halloween colors enabled today? 🎃 👻 

![screen shot 2016-10-31 at 8 59 09 am](https://cloud.githubusercontent.com/assets/6104/19854967/4f755476-9f48-11e6-9548-db171249d1df.png)
