### ISSUE TITLE
Not showing correct color when Halloween

### ISSUE THREAD

**Issue by ApolloZhu** [jasonlong/isometric-contributions#65]
I believe that it should either keeps normal (green) color, or be the same as the normal chart (orange) , but definitely not completely white.
![screen shot 2016-10-31 at 12 45 19](https://cloud.githubusercontent.com/assets/10842684/19862782/1350454e-9f68-11e6-8437-38d9062a2d7c.png)
![screen shot 2016-10-31 at 12 45 26](https://cloud.githubusercontent.com/assets/10842684/19862785/168be7fe-9f68-11e6-838f-d410c25d03f3.png)

**Comment by jasonlong** [comment]
Thanks for the report!
