### ISSUE TITLE
Isometric chart not showing Sunday contributions

### ISSUE THREAD

**Issue by oliver-newman** [jasonlong/isometric-contributions#68]
The isometric chart is only showing 6 days per week of contributions (in particular, it's leaving out all Sundays); see attached screenshot.
![screen shot 2016-12-12 at 12 24 28 pm](https://cloud.githubusercontent.com/assets/15459200/21109236/1d16f98c-c066-11e6-98c8-35ace8c84753.JPG)

**Comment by oliver-newman** [comment]
I'd be happy to look into this, though I haven't contributed to this project before and have very little prior experience with Chrome extensions, so I can't promise I'll be able to fix anything in a timely manner.

**Comment by jasonlong** [comment]
Wow, I'm not sure how I broke that! I imagine it's an easy fix though. I'll take a look shortly, but if you beat me to it, that's cool too.

**Comment by jasonlong** [comment]
I figured it out. It has to do with when we changed the size of the contribution squares a while back. I'll get a PR put together later today.

Thanks for reporting this!

**Comment by oliver-newman** [comment]
No problem, thanks for fixing it!
