### ISSUE TITLE
Year start and end date

### ISSUE THREAD

**Issue by akash-vartak** [jasonlong/isometric-contributions#72]
I guess a modification can be made to consider the starting date of the year as 1st January and not the first box in the contributions table.. For example: If i click on 2015 the `1year` should be from 1st Jan to 31st Dec but for current year it can be 1st Jan to current.
Right now, if I click on 2015, I see contributions from `Dec 28th 2014` to `Dec 31st 2015`

**Comment by jasonlong** [comment]
The 3d chart will always show exactly the same data as the 2d chart. This extension doesn't have access to any data other than what is shown on GitHub's chart. Those year links along the side are from the GitHub side and don't have anything to do with this extension.
