### ISSUE TITLE
Distribute Signed Extension for Firefox

### ISSUE THREAD

**Issue by electron0zero** [jasonlong/isometric-contributions#73]
The current extension is not signed and firefox complains about it.

so I went ahead and signed it for myself.

here is the process to sign
first clone the repo
`git clone https://github.com/jasonlong/isometric-contributions.git`
then do 
`npm install --global web-ext`
[what is web-ext?](https://github.com/mozilla/web-ext)
[Web-ext docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign)
[Web ext getting started](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext)

now go ahead and generate `JWT issuer` and `JWT secret` from [add-on developer hub](https://addons.mozilla.org/en-US/developers/addon/api/key/). it is like API key for signing the extension.

now cd into `<extension-repo>/firefox/isometric-contributions/`
then run this command to sign
` web-ext sign --api-key <your-JWT-issuer> --api-secret <your-JWT-secret>`

this should give you a signed extension(.xpi file) inside a folder named `web-ext-artifacts` inside your current working directory

**Comment by jasonlong** [comment]
Thanks for this info @electron0zero. I'm not very familiar with Firefox's extensions and didn't realize the progress they'd made since last I looked.

I've gone ahead and started the process of uploading the extension to addons.mozilla.org (ran into an error that I emailed them about) and, if I understand right, they will sign the .xpi on their end. If so, I assume I don't need to bother with the steps you listed here. Is that correct?

**Comment by electron0zero** [comment]
@jasonlong I realised that during the process of signing it got uploaded to my account and it has a UUID of `isometric-contributions@jasonlong.me` so I deleted it now.

I think that error was due to that. 
can you please retry with above-listed steps and check your email that you have used in firefox account that you used in generating keys for signing this add-on. you will have an email from `amo-editors@mozilla.org` about this add-on.

**Comment by jasonlong** [comment]
Ok, finally got the problem worked out and got the add-on submitted for review.

**Comment by electron0zero** [comment]
@jasonlong please update us with the link when gets approved.

Thanks for taking the time to look into it.

**Comment by jasonlong** [comment]
Looks like Mozilla is getting through about 7 add-ons per day in their reviewing. At this rate, they should get to mine in about a month and a half. 😒

**Comment by davidgreens** [comment]
@davidgreens

**Comment by jasonlong** [comment]
Ok, 2 months later and I'm about 60% of the way through the approval queue. Pretty absurd.

**Comment by marsjaninzmarsa** [comment]
Any update?

**Comment by jasonlong** [comment]
I gave up on their process. By the time they got around to reviewing, the extension was several versions behind and no longer worked with GitHub's DOM structure. If things improve on their end at some point, I may try again but I'm too frustrated right now.
