### ISSUE TITLE
why my color is not green ?

### ISSUE THREAD

**Issue by mrdulin** [jasonlong/isometric-contributions#74]
Yesterday, my color is green. Today, it's not. 

Is there something happened?

![image](https://cloud.githubusercontent.com/assets/17866683/23488957/b4b735e2-ff2a-11e6-9a3e-12cb54e1b842.png)

**Comment by huozhi** [comment]
Seems that github's revision cause the problem.

```coffee
COLORS = [
    new obelisk.CubeColor().getByHorizontalColor(0xeeeeee),
    new obelisk.CubeColor().getByHorizontalColor(0xd6e685),
    new obelisk.CubeColor().getByHorizontalColor(0x8cc665),
    new obelisk.CubeColor().getByHorizontalColor(0x44a340),
    new obelisk.CubeColor().getByHorizontalColor(0x1e6823)
  ]
```

The code above should be updated now.

**Comment by mrdulin** [comment]
@huozhi Thanks. I guess the reason is github modify its theme.

**Comment by jasonlong** [comment]
Sorry about this. I'll get the extension updated today.

**Comment by huozhi** [comment]
@jasonlong fast responding! awesome. 👏
