### ISSUE TITLE
Is there a way to Export the canvas object to use outside of Github?

### ISSUE THREAD

**Issue by GeorgeWL** [jasonlong/isometric-contributions#78]
On my current site I'm using https://github.com/2016rshah/githubchart-api to load a almost-live version of my ghchart, and after using this I feel that having the same canvas element on my site would look a lot better.

**Comment by jasonlong** [comment]
I was going to suggest just scraping that element from the DOM, but since it's generated from an extension that won't work. I can't think of anything automated that would work, but if anything comes to mind I'll post it here.

**Comment by jasonlong** [comment]
Closing this for now, but will reopen if any ideas come to mind.

**Comment by Akhilez** [comment]
It would be amazing to use this outside of GitHub. I'll try to tweak the code to get it useable outside.
