### ISSUE TITLE
Ballpark timeline to publish firefox addon at AMO?

### ISSUE THREAD

**Issue by talha131** [jasonlong/isometric-contributions#79]
Thank you for this addon.

Do you have any timeline in mind by which you would publish this addon's Firefox version at AMO?

It is far simpler to install from AMO, even if its beta release, then to do

> Set xpinstall.signatures.required to false in about:config. Download the isometric-contributions.xpi file and open it in Firefox Developer Edition.

**Comment by jasonlong** [comment]
I tried submitting to AMO a while back (see #73), but it was incredibly frustrating. I don't have any plans at this time to try again.
