### ISSUE TITLE
pjax support

### ISSUE THREAD

**Issue by bahlo** [jasonlong/isometric-contributions#8]
When you change tabs on a user-page, it won't replace the standard contribution graph, because just the page-content is being replaced with [pjax](http://pjax.heroku.com).

We could listen to the `pjax:end`-Event ([more info](https://github.com/defunkt/jquery-pjax#events)), but this requires injecting the whole code, not just the `icRun`.

Any thoughts on this?

**Comment by esbanarango** [comment]
:+1:

**Comment by bahlo** [comment]
🎉
