### ISSUE TITLE
[FEATURE] Average Contributions

### ISSUE THREAD

**Issue by Pl4gue** [jasonlong/isometric-contributions#81]
Hey @jasonlong !

I really love your extension and want to give you a huge credit for coming up with and implementing this idea!

However, I recently thought that it would be really nice to see my average contributions per day.
What do you think about this? If possible, I would also like to work on this!

**Comment by jasonlong** [comment]
@Pl4gue I'm not opposed to the idea, but I just want to make sure the amount of stats displayed doesn't get overwhelming.

I'd rather not add another full-sized stat block like the others. Maybe something more subtle like this?

![image](https://user-images.githubusercontent.com/6104/36438986-86def192-1639-11e8-8a54-34911b328d0a.png)

**Comment by Pl4gue** [comment]
Yeah I absolutely agree with you @jasonlong 😄 
Your idea sounds good 👍 So shall I try implementing it?

**Comment by jasonlong** [comment]
Sure, give it a try!

**Comment by Pl4gue** [comment]
Alright 😃 Will be starting by the new week :)

**Comment by Pl4gue** [comment]
Small question: How did you do this quick small visual mockup in your first comment? Just plain photo editing?

**Comment by jasonlong** [comment]
Yeah just took a screenshot and played with it in Sketch.
