### ISSUE TITLE
Streak is wrong

### ISSUE THREAD

**Issue by ljharb** [jasonlong/isometric-contributions#85]
On my profile, your extension reports my streak as 369 days. However, my correct streak (which the "Github Original Streak" chrome extension reports correctly) is 1478 days.

It'd be great if you showed the correct count :-)

**Comment by jasonlong** [comment]
Yeah I wish I could get the full streak, but if it’s longer than a year the extension can’t see it. I only have access to the contributions on the page.

**Comment by ljharb** [comment]
Then how can the other chrome extension see it? It’s clearly possible.

**Comment by jasonlong** [comment]
It’s possible by paginating through previous years with additional requests. I’m not interested in this tbh and have considered removing streaks from the extension altogether.

**Comment by ljharb** [comment]
Gotcha. That’s unfortunate, why?

**Comment by jasonlong** [comment]
Basically for the same reasons we removed streaks on github.com. We don't want to encourage people to string together endless days of work as it's not a healthy behavior. Besides, it's an easy metric to game and ultimately doesn't mean much.
