### ISSUE TITLE
No longer able to toggle between normal and isometric charts

### ISSUE THREAD

**Issue by d4nyll** [jasonlong/isometric-contributions#88]
With the introduction of the [Profile activity overview](https://blog.github.com/changelog/2018-08-24-profile-activity-overview/) feature from GitHub, I am no longer getting the toggle button to switch between the normal and isometric charts.

![screenshot from 2018-08-25 14-39-59](https://user-images.githubusercontent.com/9997953/44618789-cfc0ec80-a874-11e8-94f1-ef970e4d8f3c.png)

**Comment by jasonlong** [comment]
Thanks for the report. I'll get this fixed up soon.
