### ISSUE TITLE
"{{n}} contributions" overlapping with chart

### ISSUE THREAD

**Issue by schwartzadev** [jasonlong/isometric-contributions#91]
## System Info

| Data                    | Key |
| ------------------ | ---------------------------------------------------------- |
| Google Chrome | 68.0.3440.106 (Official Build) (64-bit) (cohort: Stable)
| OS | Windows
JavaScript | V8 6.8.275.26

See the image below for the overlap.
![chrome_2018-09-02_12-54-57](https://user-images.githubusercontent.com/18607205/44959676-92c9ab00-aeaf-11e8-87f2-fc257793f0bb.png)

Loving the extension 👍 . Let me know if you need any more information.

**Comment by jasonlong** [comment]
Thanks for the report @schwartzadev. I'll take a look at this shortly.
