### ISSUE TITLE
A bug in Chrome

### ISSUE THREAD

**Issue by hzb** [jasonlong/isometric-contributions#95]
Chrome version:  69.0.3497.100 (Official Build) (64-bit)
Isometric-contributions: latest
Bug:

![screen-shot-2018-09-18-at-11 14 26-am](https://user-images.githubusercontent.com/535675/45662493-c0138b80-bb34-11e8-919f-45ce0bf0d102.jpg)

Six days a week?

**Comment by jasonlong** [comment]
Yikes, thanks for that report. I hadn't even noticed that.

**Comment by hzb** [comment]
@jasonlong Welcome :)

**Comment by beta** [comment]
In my situation the Sunday row is gone, and the bars are lower than other rows.

Chrome version: 69.0.3497.100 (Official Build) (64-bit)
System version: macOS High Sierra 10.13.1
Isometric Contributions version: 1.0.24

![image](https://user-images.githubusercontent.com/5000910/45706477-ee35b180-bbae-11e8-9c57-c0350f5b8da5.png)
