### ISSUE TITLE
Graph not rendered correctly 🐛

### ISSUE THREAD

**Issue by samjudge** [jasonlong/isometric-contributions#99]
When you visit a page with from/to query parameters set in the github url the isometric graph will be rendered weirdly (in this case, the url is https://github.com/samjudge?tab=overview&from=2018-11-01&to=2018-11-29)

![image](https://user-images.githubusercontent.com/6123140/49223576-1162b580-f3d7-11e8-8297-27558bebe8b6.png)

This is in Version 70.0.3538.110 of Chrome (Latest)

**Comment by jasonlong** [comment]
Thanks for the report @samjudge. I'll check this out soon.
